# -*- coding: utf-8 -*-
"""API-Flask-DIO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sbyI6ov2qbvzGjyez3DaWDqPUcKN5KmZ

Para instalar o pacote flask_ngrok, você pode utilizar o comando pip no seu ambiente Python. Execute o seguinte comando no terminal:
"""

!pip install flask_ngrok

"""Vamos importar as bibliotecas que usaremos:"""

import pandas as pd
from flask_ngrok import run_with_ngrok
from flask import request, jsonify, Flask
import random as rk

"""Criando uma instância do objeto Flask, que é a base dessa aplicação."""

app = Flask(__name__) #the name of the application package
run_with_ngrok(app)

"""Agora, vamos criar uma entrada para a API que estará na forma de um dicionário ou (JSON):"""

d = {
    "name": "Nikola",
    "surname": "Tesla",
    "idade": 60
      }

"""
Definindo uma rota raiz ("/") para a página inicial:"""

@app.route("/") #code to assign HomePage URL in our app to function home.

def home():
  '''
  The entire line below must be written in a single line.
  '''
  return "<marquee><h3> TO CHECK IN PUT ADD '/input' TO THE URL AND TO CHECK OUT PUT ADD '/output' TO THE URL.</h3></marquee>"

"""Definindo uma rota /input:"""

@app.route("/input") #code to assign Input URL in our app to function input.

def input():
  return jsonify(d) # "d" is the dictionary we defined

"""Definindo uma rota /output e implementa uma função chamada newJson para lidar com solicitações para essa rota:"""

@app.route('/output', methods=['GET','POST']) #output page

def newJson():
 pred = r.choice(["positive","negative"])
 nd = d # our input
 nd["prediction"]=pred
 return jsonify(nd)

app.run()